export type CommitData = {
  hash: string;
  message: string;
  diff: string;
  timestamp: number;
  repoName?: string;
  source?: string;
  annotation?: string;
};

export type AnnotationSource = "commit_message" | "user" | "ai";
export type AnnotationColor = "yellow" | "blue";
export type AnnotationMode = "skip" | "manual" | "ai" | "manual_and_ai";

export type AnnotationRecord = {
  id: string;
  nodeId: string;
  commitHash: string;
  source: AnnotationSource;
  content: string;
  color?: AnnotationColor;
  createdAt: number;
};

export type AnnotationChoiceTarget = {
  nodeId: string;
  commitHash: string;
  branchId: string;
  summary: string;
  type: CommitType | string;
  screenshotPath: string;
};

export type AnnotationChoice = {
  nodeId?: string;
  branchId?: string;
  screenshotPath?: string;
  mode: AnnotationMode;
  annotation?: string;
};

// On-screen geometry of a located element, in page (document) pixels. pageW/pageH
// are the full scrollable document dimensions, so the spatial board can lay every
// component out in one shared coordinate system.
export type NodeGeometry = {
  x: number;
  y: number;
  w: number;
  h: number;
  pageW: number;
  pageH: number;
};

export type ScreenshotTarget = {
  // How to locate the changed element (or full page). For a non-full target we
  // screenshot/measure the located element's immediate parent container, which
  // defines this component's branch and drives the recorded geometry.
  mode: "full" | "selector" | "text" | "role";
  value?: string;
};

export type CommitType = "UI_CHANGE" | "FEATURE" | "REFACTOR" | "UNKNOWN";

// One changed component detected by the LLM within a single commit. A commit can
// change several components, so analysis returns a list of these.
export type ComponentChange = {
  component: string; // stable id; "" or "main" => the main branch (broad/global change)
  parentBranch?: string; // NEW component only: existing branch to nest under ("" => main)
  summary: string;
  type: CommitType;
  path?: string; // route to navigate to before this component's capture; defaults to "/"
  screenshotTarget: ScreenshotTarget;
};

export type CommitAnalysis = {
  components: ComponentChange[];
};

// A single component change for one commit — the node of the design graph.
export type IterationNode = {
  id: string; // `${commitHash}:${branchId}`
  commitHash: string;
  branchId: string;
  parentId: string | null; // previous node on the SAME component branch, null if first
  summary: string;
  // Richer, design-oriented annotation (What changed + a hedged guess at Why)
  // generated by a vision pass over the captured screenshot. Undefined for
  // nodes captured before annotations existed, or when annotation was skipped.
  annotation?: string;
  type: CommitType;
  screenshotPath: string; // relative path into the nested branch-tree mirror, e.g. captures/<repo>/main/sidebar/<NNN>-<shortHash>.png
  timestamp: number;
  // On-screen rect of the captured container at capture time (the climbed
  // `capture` element, or the located element when no container was chosen).
  // Undefined for nodes captured before geometry tracking existed, or whose
  // capture fell back to full page.
  geometry?: NodeGeometry;
};

// A component branch — the node of the component tree.
export type BranchRecord = {
  id: string; // "main" | "<component>"
  parentBranchId: string | null; // null for main; component nesting (LLM-driven)
  forkNodeId: string | null; // parent-branch tip node this split from (fork point)
  createdAt: number;
  // How to re-screenshot this branch's component on demand (e.g. for cascading
  // ancestor updates). navPath is the route to navigate to; target is the
  // component locator. Undefined for legacy branches created before this existed.
  navPath?: string;
  target?: ScreenshotTarget;
};

// Result of capturing one screenshot job: the file it wrote and, when a concrete
// element was located, that element's on-screen geometry. `branchId`/`label`/
// `selector` describe the captured container's stable DOM identity (the basis
// for grouping); `branchId` is "main" when the capture fell back to full page.
// `componentKey` is the full, route-scoped DOM identity key used to recognize the
// same component across commits and to group it in the component library.
export type ScreenshotResult = {
  jobId?: string;
  outputPath: string;
  geometry?: NodeGeometry;
  branchId?: string;
  componentKey?: string;
  label?: string;
  selector?: string;
  navPath?: string;
  // For a highlight capture (a full-page shot with the changed containers
  // outlined): how many containers were actually located and outlined. 0 means
  // nothing could be highlighted, so the caller should discard the capture.
  highlightCount?: number;
};

// ---------------------------------------------------------------------------
// Three-tree data model (the SQLite source of truth).
//
// Tree 1 (Main view): Page -> Component -> ComponentVersion, stored as a single
// adjacency table of nodes (`kind` discriminates the level). Tree 2 (Component
// Library): one persisted LLM classification per component. Tree 3 (Commit
// overview): one full-page screenshot per commit x changed route.
// ---------------------------------------------------------------------------

export type Tree1Kind = "page" | "component" | "version";

// One row of the Tree 1 adjacency table. A `page` is a route (parent null), a
// `component` is a DOM container on that page (parent = page), and a `version`
// is one captured iteration of that component (parent = component). Page and
// component rows always mirror the LATEST screenshot; version rows are the
// immutable chronological history.
export type Tree1NodeRecord = {
  id: string;
  kind: Tree1Kind;
  parentId: string | null;
  navPath: string | null;
  componentKey: string | null;
  label: string | null;
  commitHash: string | null;
  screenshotPath: string;
  screenshotHash: string | null;
  summary: string;
  annotation?: string;
  type: CommitType;
  createdAt: number;
  timestamp: number;
  geometry?: NodeGeometry;
};

// One persisted component-library classification, keyed by the component's
// stable DOM identity key so it is reused across commits rather than
// re-classified. `screenshotPath`/`screenshotHash` track the component's latest
// captured screenshot so the library view shows its current look.
export type Tree2Classification = {
  componentKey: string;
  groupName: string;
  label: string | null;
  screenshotPath: string;
  screenshotHash: string | null;
  classifiedAt: number;
};

// One full-page screenshot captured for a commit on a given route. The overall
// view of what that commit changed on that page.
export type Tree3CommitScreenshot = {
  id: string; // `${commitHash}:${navPath}`
  commitHash: string;
  navPath: string | null;
  screenshotPath: string;
  screenshotHash: string | null;
  summary: string;
  timestamp: number;
  pageW?: number;
  pageH?: number;
  // A second full-page screenshot of the SAME page with the changed DOM
  // containers outlined by a red dotted border. The original screenshotPath is
  // left untouched; this highlighted variant branches off it in the commit
  // overview tree. Undefined when no container could be highlighted on the page.
  highlightScreenshotPath?: string;
  highlightScreenshotHash?: string;
};

// One container captured while climbing the live DOM ancestor chain above a
// job's located element. branchId is derived from the container's stable DOM
// identity (a shortest anchored DOM path), or "main" for the full-page capture
// taken once the climb reaches body/html. selector is a best-effort valid CSS
// selector to re-locate the container on demand.
export type AncestorCapture = {
  branchId: string;
  outputPath: string;
  geometry?: NodeGeometry;
  navPath: string; // route the ancestor was captured on
  label?: string;
  selector?: string;
};

export type PageContext = {
  path: string;
  elements: UiElement[];
};

export type UiElement = {
  tag: string;
  id?: string;
  classes: string[];
  role?: string;
  testid?: string;
  text?: string;
  // Best-effort selector for the nearest identifiable ancestor (id/class), useful
  // as context when assigning component nesting.
  parent?: string;
};
